// ===== ChatFlow sample data (Korean) =====
const AV = {
  me:    { name: '윤도현', color: 'linear-gradient(135deg,#ff7a59,#ff5b8a)', initial: '윤' },
  minjun:{ name: '김민준', color: 'linear-gradient(135deg,#5b8cff,#3b6fe0)', initial: '민' },
  seoyeon:{name: '이서연', color: 'linear-gradient(135deg,#22c19a,#12a37f)', initial: '서' },
  jihoon:{ name: '박지훈', color: 'linear-gradient(135deg,#9b5cff,#7a3bd8)', initial: '지' },
  hayoung:{name: '정하영', color: 'linear-gradient(135deg,#f0b232,#e0962a)', initial: '하' },
  woojin:{ name: '최우진', color: 'linear-gradient(135deg,#ff6b9d,#e84d7f)', initial: '우' },
  eunbi: { name: '한은비', color: 'linear-gradient(135deg,#3bc4e0,#2399b8)', initial: '은' },
  taeho: { name: '강태호', color: 'linear-gradient(135deg,#7d8590,#5a626b)', initial: '태' },
};

// participants per room
const ROOMS = [
  {
    id: 'design',
    type: 'group',
    name: '디자인팀 🎨',
    avatarColor: 'linear-gradient(135deg,#ff7a59,#ff4f8b)',
    avatarInitial: '디',
    square: true,
    desc: 'ChatFlow 제품 디자인 전체 채널',
    unread: 3,
    members: ['me','minjun','seoyeon','jihoon','hayoung','woojin','eunbi','taeho'],
    online: ['me','minjun','seoyeon','hayoung','eunbi'],
    messages: [
      { from:'seoyeon', t:'09:12', d:'오늘', text:'다들 좋은 아침이에요 ☀️ 어제 공유한 메인 화면 시안 다들 보셨죠?' },
      { from:'minjun', t:'09:14', text:'네 봤어요! 우측 패널에 참여자 목록 들어간 거 너무 좋던데요 👍' },
      { from:'me', t:'09:15', text:'감사합니다 ㅎㅎ 다크모드 톤을 좀 더 뉴트럴하게 잡아봤어요.' },
      { from:'me', t:'09:15', text:'코랄 포인트 컬러가 생각보다 잘 어울리는 것 같아요.', read:true },
      { from:'hayoung', t:'09:21', text:'코랄 진짜 예뻐요. 근데 안읽은 메시지 뱃지 색이랑 살짝 겹치지 않을까요?' },
      { from:'me', t:'09:23', text:'그 부분 고민했는데, 뱃지는 채도를 조금 더 높여서 구분되게 했어요. 우측에서 보여드릴게요!', read:true },
      { from:'eunbi', t:'09:30', text:'타이핑 인디케이터 애니메이션도 추가됐다던데 데모 가능할까요? 👀' },
    ],
  },
  {
    id: 'minjun',
    type: 'dm',
    name: '김민준',
    avatarColor: 'linear-gradient(135deg,#5b8cff,#3b6fe0)',
    avatarInitial: '민',
    desc: '프론트엔드 개발자',
    status: 'online',
    unread: 0,
    members: ['me','minjun'],
    online: ['me','minjun'],
    messages: [
      { from:'minjun', t:'어제', d:'어제', text:'도현님, 메시지 컴포넌트 마크업 좀 봐주실 수 있어요?' },
      { from:'me', t:'어제', text:'그럼요, 지금 시간 괜찮아요.', read:true },
      { from:'minjun', t:'08:40', d:'오늘', text:'말풍선 라운드 값이 디자인이랑 살짝 다른 것 같아서요 🤔' },
      { from:'minjun', t:'08:40', text:'내 메시지는 우측 상단만 각지게, 상대는 좌측 상단만 각지게 맞죠?' },
      { from:'me', t:'08:42', text:'맞아요! 꼬리 방향이라고 생각하면 편해요. 토큰값 정리해서 보낼게요.', read:false },
    ],
  },
  {
    id: 'frontend',
    type: 'group',
    name: '프론트엔드 개발 💻',
    avatarColor: 'linear-gradient(135deg,#5b8cff,#7a3bd8)',
    avatarInitial: '프',
    square: true,
    desc: 'ChatFlow 웹 클라이언트 개발 채널',
    unread: 12,
    members: ['me','minjun','jihoon','taeho','woojin'],
    online: ['me','minjun','jihoon'],
    messages: [
      { from:'jihoon', t:'10:02', d:'오늘', text:'실시간 소켓 재연결 로직 머지했습니다. 리뷰 부탁드려요 🙏' },
      { from:'taeho', t:'10:05', text:'오 빠르네요. 읽음 처리 이벤트도 같이 들어갔나요?' },
      { from:'jihoon', t:'10:06', text:'네 read receipt 이벤트 같이 넣었어요. QA 통과하면 바로 배포 가능합니다.' },
      { from:'me', t:'10:11', text:'좋아요 👏 디자인 쪽 읽음 표시 UI는 시안대로 들어가 있으니 확인 부탁해요!', read:true },
    ],
  },
  {
    id: 'seoyeon',
    type: 'dm',
    name: '이서연',
    avatarColor: 'linear-gradient(135deg,#22c19a,#12a37f)',
    avatarInitial: '서',
    desc: '프로덕트 디자이너',
    status: 'online',
    unread: 1,
    members: ['me','seoyeon'],
    online: ['me','seoyeon'],
    messages: [
      { from:'seoyeon', t:'11:20', d:'오늘', text:'도현님! 사이드바 검색창 포커스 상태 컬러 어떤 걸로 갈까요?' },
      { from:'seoyeon', t:'11:20', text:'코랄 보더로 통일하는 게 좋을 것 같은데 의견 궁금해요 🙂' },
    ],
  },
  {
    id: 'notice',
    type: 'group',
    name: '📢 전사 공지',
    avatarColor: 'linear-gradient(135deg,#f0b232,#e0962a)',
    avatarInitial: '공',
    square: true,
    desc: '회사 전체 공지 채널',
    unread: 0,
    muted: true,
    members: ['me','hayoung','taeho','minjun','seoyeon','jihoon','woojin','eunbi'],
    online: ['me','hayoung','minjun','seoyeon','eunbi'],
    messages: [
      { from:'hayoung', t:'화요일', d:'화요일', text:'이번 주 금요일 전사 워크샵 안내드립니다. 자세한 일정은 캘린더 확인 부탁드려요!' },
      { from:'taeho', t:'화요일', text:'참석 확인했습니다 ✅' },
    ],
  },
  {
    id: 'climb',
    type: 'group',
    name: '주말 등산 모임 ⛰️',
    avatarColor: 'linear-gradient(135deg,#22c19a,#3bc4e0)',
    avatarInitial: '산',
    square: true,
    desc: '주말마다 산으로!',
    unread: 0,
    members: ['me','woojin','eunbi','taeho'],
    online: ['me','eunbi'],
    messages: [
      { from:'woojin', t:'금요일', d:'금요일', text:'이번 주말 북한산 어떠세요? 날씨 좋다는데 🏔️' },
      { from:'eunbi', t:'금요일', text:'저 콜이요!! 몇 시에 만날까요?' },
      { from:'me', t:'금요일', text:'9시 정도 어때요? 너무 늦으면 더워서요 ㅋㅋ', read:true },
    ],
  },
];

const ME = 'me';
Object.assign(window, { AV, ROOMS, ME });
